pybo/models.py
from pybo import db

class Question(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    subject = db.Column(db.String(200), nullable=False)
    content = db.Column(db.Text(), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)

class Answer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    question_id = db.Column(db.Integer, db.ForeignKey('question.id', ondelete='CASCADE'))
    question = db.relationship('Question', backref=db.backref('answer_set', cascade='all, delete-orphan'))
    content = db.Column(db.Text(), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)
    

# data 만들고 테스트 해볼 것  
# answer = Answer.query.get(id=2)
# answer.question.answer_set

# question = Question.query.get(id=2)
# question.answer_set

pybo/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField
from wtforms.validators import DataRequired

class QuestionForm(FlaskForm):
    subject = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Questions', validators=[DataRequired()])

class AnswerForm(FlaskForm):
    content = TextAreaField('Answers', validators=[DataRequired()])

pybo/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

import config

db = SQLAlchemy()
migrate = Migrate()



def create_app():
    from .views import main_views
    from .views import question_views
    from .views import answer_views
    from . import models
    
    app = Flask(__name__)
    app.config.from_object(config)
    
    # ORM
    db.init_app(app)
    migrate.init_app(app, db)
    
    # Blueprint
    app.register_blueprint(main_views.bp)
    app.register_blueprint(question_views.bp)
    app.register_blueprint(answer_views.bp)
    
    return app

pybo/views/answer_views.py
from datetime import datetime
from flask import Blueprint
from flask import url_for
from flask import request
from flask import render_template
from werkzeug.utils import redirect
from .. import db
from ..forms import AnswerForm
from ..models import Question
from ..models import Answer


bp = Blueprint('answer', __name__, url_prefix='/answer')

@bp.route('/create/<int:qid>', methods=('POST',))
def create(qid):
    form = AnswerForm()
    q = Question.query.get_or_404(qid)
    if form.validate_on_submit():
        c = request.form['content']
        a = Answer(question=q, content=c, create_date=datetime.now())
        db.session.add(a)
        db.session.commit()
        return redirect(url_for('question.detail', qid=qid))
    return render_template('question/question_detail.html', q=q, form=form)

pybo/views/main_views.py
from flask import Blueprint
from flask import url_for
from werkzeug.utils import redirect


bp = Blueprint('main', __name__, url_prefix='/')


@bp.route('/hello')
def hello_pybo():
    return 'Hello, Pybo!'

@bp.route('/')
def index():
    return redirect(url_for('question._list'))

pybo/views/question_views.py
from datetime import datetime
from flask import Blueprint
from flask import render_template
from flask import request
from flask import url_for
from werkzeug.utils import redirect

from .. import db
from ..models import Question
from ..forms import QuestionForm
from ..forms import AnswerForm


bp = Blueprint('question', __name__, url_prefix='/question')


@bp.route('/list/')
def _list():
    q_list = Question.query.order_by(Question.create_date.desc())
    return render_template('question/question_list.html', q_list=q_list)

@bp.route('/detail/<int:qid>/')
def detail(qid):
    form = AnswerForm()
    q = Question.query.get_or_404(qid)
    return render_template('question/question_detail.html', q=q, form=form)

@bp.route('/create/', methods=('GET', 'POST'))
def create():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        q = Question(subject=form.subject.data, content=form.content.data, create_date=datetime.now())
        db.session.add(q)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('question/question_form.html', form=form)

pybo/templates/base.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
    />
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='bootstrap.min.css') }}"
    />
    <!-- pybo CSS -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='style.css') }}"
    />
    <title>Hello, pybo!</title>
  </head>
  <body>
    {% block content %} {% endblock %}
  </body>
</html>

pybo/templates/question/question_detail.html
{% extends 'base.html' %} {% block content %}
<div class="container my-3">
  <!-- Questions -->
  <h2 class="border-bottom py-2">{{ q.subject }}</h2>
  <div class="card my-3">
    <div class="card-body">
      <div class="card-text" style="white-space: pre-line">{{ q.content }}</div>
      <div class="d-flex justify-content-end">
        <div class="badge bg-light text-dark p-2">{{ q.create_date }}</div>
      </div>
    </div>
  </div>

  <!-- Answer List -->
  <h5 class="border-bottom my-3 py-2">{{ q.answer_set|length }} Answers</h5>
  {% for a in q.answer_set %}
  <div class="card my-3">
    <div class="card-body">
      <div class="card-text" style="white-space: pre-line">{{ a.content }}</div>
      <div class="d-flex justify-content-end">
        <div class="badge bg-light text-dark p-2">{{ a.create_date }}</div>
      </div>
    </div>
  </div>
  {% endfor %}

  <!-- Post New Answers -->
  <form
    action="{{ url_for('answer.create', qid=q.id) }}"
    method="post"
    class="my-3"
  >
    {{ form.csrf_token }}
    <!-- Error Code Start -->
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      {% for field, errors in form.errors.items() %}
      <strong>{{ form[field].label }}</strong>
      <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endfor %}
    </div>
    {% endif %}
    <!-- Error Code End-->
    <div class="mb-3">
      <textarea
        name="content"
        id="content"
        class="form-control"
        rows="10"
      ></textarea>
    </div>
    <input type="submit" value="Post Answer" class="btn btn-primary" />
  </form>
</div>
{% endblock %}

pybo/templates/question/question_form.html
{% extends 'base.html' %} {% block content %}
<!-- Post New Question -->
<div class="container">
  <h5 class="my-3 border-bottom pb-2">Ask a Question</h5>
  <form method="post" class="my-3">
    {{ form.csrf_token }}
    <!-- Error Code Start -->
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      {% for field, errors in form.errors.items() %}
      <strong>{{ form[field].label }}</strong>
      <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endfor %}
    </div>
    {% endif %}
    <!-- Error Code End-->
    <div class="mb-3">
      <label for="subject">Title</label>
      <input
        type="text"
        class="form-control"
        name="subject"
        id="subject"
        value="{{ form.subject.data or ''}}"
      />
    </div>
    <div class="mb-3">
      <label for="content">Questions</label>
      <textarea class="form-control" name="content" id="content" rows="10">
{{ form.content.data or ''}}</textarea
      >
    </div>
    <!-- When Utilizing Code for Automatic HTML Generation by Forms -->
    <!-- {{ form.subject.label }} {{ form.subject(class="form-control") }} {{
    form.content.label }} {{ form.content(class="form-control") }} -->
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
</div>
{% endblock %}

pybo/templates/question/question_list.html
{% extends 'base.html' %} {% block content %}
<div class="container my-3">
  <table class="table">
    <thead>
      <tr class="table-dark">
        <th>No.</th>
        <th>Title</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
      {% if q_list %} {% for q in q_list %}
      <tr>
        <td>{{ loop.index }}</td>
        <td>
          <a href="{{ url_for('question.detail', qid=q.id) }}"
            >{{ q.subject }}</a
          >
        </td>
        <td>{{ q.create_date }}</td>
      </tr>
      {% endfor %} {% else %}
      <tr>
        <td colspan="3">No Questions.</td>
      </tr>
      {% endif %}
    </tbody>
  </table>
  <a href="{{ url_for('question.create') }}" class="btn btn-primary"
    >New Post</a
  >
</div>
{% endblock %}